### ISSUE TITLE
Setting imported cookies directly in profile writer 

### ISSUE THREAD

**Issue by darkdh** [brave/muon#320]
Instead of emitting to browser-laptop and circle back to set cookies in muon

**Comment by bpowers** [comment]
A couple of thoughts I had that I'll post here @darkdh, since they sort of span both PRs:

`ShouldSkipCookie` has a test case in `browser-laptop`, but not in `muon`.  I think you said this is all right, as there doesn't seem to be a unit testing setup in electron.  Is that right?

Similarly, I didn't actually remove `shouldSetCookie` from `importer.js` -- but the only user is the unit test at this point, so that could be added to brave/browser-laptop#11687 .  Let me know if that makes sense, and I can make that change.

**Comment by darkdh** [comment]
we should remove ti along with the unit test too. We will have muon unit test in the near future

**Comment by bsclifton** [comment]
Closing as stale
